### ISSUE TITLE
The seaborn requirement should be added to `install_requires` in `setup.py`

### ISSUE THREAD

**Issue by jonrkarr** [ASinanSaglam/PyBioNetGen#2]

**Comment by ASinanSaglam** [comment]
Thank you for looking at the repo Jonathan! I most likely will continue development with https://github.com/RuleWorld/PyBioNetGen instead of the one on my personal account. I'll sync them up, fix the issues you posted in this repo and then push it down to RuleWorld but I suggest using that one as the base. I'll fix these and update you in each as I do so.

**Comment by ASinanSaglam** [comment]
Addressed in [new commit](https://github.com/ASinanSaglam/PyBioNetGen/commit/411b5ce2ca08559770a7b3f22f582313766e33a6)
